// Mapa oficial de condições da WeatherAPI traduzido para português.
// Chave: code numérico (estável). Valor: tradução para dia e noite.
// Fonte: https://www.weatherapi.com/docs/weather_conditions.json

const WEATHER_CONDITIONS = {
  1000: { day: 'Ensolarado', night: 'Limpo' },
  1003: { day: 'Parcialmente nublado', night: 'Parcialmente nublado' },
  1006: { day: 'Nublado', night: 'Nublado' },
  1009: { day: 'Encoberto', night: 'Encoberto' },
  1012: { day: 'Névoa seca', night: 'Névoa seca' },
  1015: { day: 'Névoa de poeira', night: 'Névoa de poeira' },
  1018: { day: 'Poeira soprando', night: 'Poeira soprando' },
  1021: { day: 'Tempestade de poeira', night: 'Tempestade de poeira' },
  1024: { day: 'Tempestade de areia', night: 'Tempestade de areia' },
  1027: { day: 'Tempestade de areia severa', night: 'Tempestade de areia severa' },
  1030: { day: 'Névoa', night: 'Névoa' },
  1033: { day: 'Fumaça', night: 'Fumaça' },
  1036: { day: 'Névoa de fumaça', night: 'Névoa de fumaça' },
  1039: { day: 'Poluição atmosférica', night: 'Poluição atmosférica' },
  1042: { day: 'Poluição atmosférica severa', night: 'Poluição atmosférica severa' },
  1045: { day: 'Poeira do Saara', night: 'Poeira do Saara' },
  1048: { day: 'Poeira', night: 'Poeira' },
  1063: { day: 'Possibilidade de chuva isolada', night: 'Possibilidade de chuva isolada' },
  1066: { day: 'Possibilidade de neve isolada', night: 'Possibilidade de neve isolada' },
  1069: { day: 'Possibilidade de aguaceiro isolado', night: 'Possibilidade de aguaceiro isolado' },
  1072: { day: 'Possibilidade de garoa congelante isolada', night: 'Possibilidade de garoa congelante isolada' },
  1087: { day: 'Possibilidade de trovoadas', night: 'Possibilidade de trovoadas' },
  1114: { day: 'Neve soprando', night: 'Neve soprando' },
  1117: { day: 'Nevasca', night: 'Nevasca' },
  1135: { day: 'Neblina', night: 'Neblina' },
  1147: { day: 'Neblina congelante', night: 'Neblina congelante' },
  1150: { day: 'Garoa fraca isolada', night: 'Garoa fraca isolada' },
  1153: { day: 'Garoa fraca', night: 'Garoa fraca' },
  1168: { day: 'Garoa congelante', night: 'Garoa congelante' },
  1171: { day: 'Garoa congelante forte', night: 'Garoa congelante forte' },
  1180: { day: 'Chuva fraca isolada', night: 'Chuva fraca isolada' },
  1183: { day: 'Chuva fraca', night: 'Chuva fraca' },
  1186: { day: 'Chuva moderada por vezes', night: 'Chuva moderada por vezes' },
  1189: { day: 'Chuva moderada', night: 'Chuva moderada' },
  1192: { day: 'Chuva forte por vezes', night: 'Chuva forte por vezes' },
  1195: { day: 'Chuva forte', night: 'Chuva forte' },
  1198: { day: 'Chuva congelante fraca', night: 'Chuva congelante fraca' },
  1201: { day: 'Chuva congelante moderada ou forte', night: 'Chuva congelante moderada ou forte' },
  1204: { day: 'Aguaceiro fraco', night: 'Aguaceiro fraco' },
  1207: { day: 'Aguaceiro moderado ou forte', night: 'Aguaceiro moderado ou forte' },
  1210: { day: 'Neve fraca isolada', night: 'Neve fraca isolada' },
  1213: { day: 'Neve fraca', night: 'Neve fraca' },
  1216: { day: 'Neve moderada isolada', night: 'Neve moderada isolada' },
  1219: { day: 'Neve moderada', night: 'Neve moderada' },
  1222: { day: 'Neve forte isolada', night: 'Neve forte isolada' },
  1225: { day: 'Neve forte', night: 'Neve forte' },
  1237: { day: 'Granizo miúdo', night: 'Granizo miúdo' },
  1240: { day: 'Pancada de chuva fraca', night: 'Pancada de chuva fraca' },
  1243: { day: 'Pancada de chuva moderada ou forte', night: 'Pancada de chuva moderada ou forte' },
  1246: { day: 'Pancada de chuva torrencial', night: 'Pancada de chuva torrencial' },
  1249: { day: 'Pancadas de aguaceiro fraco', night: 'Pancadas de aguaceiro fraco' },
  1252: { day: 'Pancadas de aguaceiro moderado ou forte', night: 'Pancadas de aguaceiro moderado ou forte' },
  1255: { day: 'Pancadas de neve fraca', night: 'Pancadas de neve fraca' },
  1258: { day: 'Pancadas de neve moderada ou forte', night: 'Pancadas de neve moderada ou forte' },
  1261: { day: 'Pancadas de granizo miúdo fraco', night: 'Pancadas de granizo miúdo fraco' },
  1264: { day: 'Pancadas de granizo miúdo moderado ou forte', night: 'Pancadas de granizo miúdo moderado ou forte' },
  1273: { day: 'Chuva fraca isolada com trovoada', night: 'Chuva fraca isolada com trovoada' },
  1276: { day: 'Chuva moderada ou forte com trovoada', night: 'Chuva moderada ou forte com trovoada' },
  1279: { day: 'Neve fraca isolada com trovoada', night: 'Neve fraca isolada com trovoada' },
  1282: { day: 'Neve moderada ou forte com trovoada', night: 'Neve moderada ou forte com trovoada' },
};

module.exports = WEATHER_CONDITIONS;
